### ISSUE TITLE
Wrong data file for the fb dataset

### ISSUE THREAD

**Issue by alihadian** [learnedsystems/SOSD#10] opened 2020-07-06 14:06 UTC
In the new benchmark (VLDB 2020), the ```fb_200M_uint64``` dataset is wrong. It's not the facebook IDs, but it is actually the lognormal dataset.

Here is the distribution of ```data/fb_200M_uint64``` on the new benchmark (```vldb_2020``` tag):
![image](https://user-images.githubusercontent.com/3843633/86601825-b7a27400-bf99-11ea-9a2d-21531b4a502a.png)

The fb data used to be like a uniform distribution. Here is the plot of the fb dataset downloaded by the earlier scripts in ```mlforsys19``` tag:
![image](https://user-images.githubusercontent.com/3843633/86602031-00f2c380-bf9a-11ea-9fb4-32b2649526bf.png)

Would you please correct the download scripts?
Also, are the VLDB paper results for the new or old fb file?

**Comment by RyanMarcus** [comment] 2020-07-06 15:29
I believe this is actually correct -- when we first got the FB dataset, we hadn't realized the original authors had smoothed out several outliers at the end of the file. In the new version, we've restored those original outliers.

To see that the distribution is different from lognormal, plot all the keys but the last 1000.

See also the discussion in S4.2 on the arXiv draft, "Performance of RBS."

**Comment by alihadian** [comment] 2020-07-06 18:10
Interesting. Thanks for the clarification.

**Comment by alihadian** [comment] 2020-07-07 10:45
> I believe this is actually correct -- when we first got the FB dataset, we hadn't realized the original authors had smoothed out several outliers at the end of the file. In the new version, we've restored those original outliers.
> 
> To see that the distribution is different from lognormal, plot all the keys but the last 1000.
> 
> See also the discussion in S4.2 on the arXiv draft, "Performance of RBS."

I understand this, but then it would make the comparison unfair. For example, RadixBinarySearch suffers from the outliers but RadixSpine (which has almost the same nature) is manually set not to consider the last 200 records:

https://github.com/learnedsystems/SOSD/blob/3b52d0934f886e4ddc91622b1e23f5b32d74d11d/competitors/radix_spline.h#L193

Wouldn't it be more convenient to just revert back to the original FB dataset in the MLforSys paper? I don't think it is a common case in real-world to have a uniform distribution with only 0.0000125% outliers in such extremely different scale.

**Comment by RyanMarcus** [comment] 2020-07-07 14:55
@alexandervanrenen @andreaskipf  we put in this hack for radix spline because the new version, which wasn't released yet, could handle such outliers automatically. Is this the case? If so, can we please get the new code merged ASAP? If not, we need to remove the hack and show the degraded RS numbers.

I don't think it is fruitful to argue over if extreme outliers are or are not common in real world data. 2^64-x is often used to mark a special value (e.g., PostgreSQL NULLs and default flags). I think there's obvious utility in having at least one dataset that contains them. 

Of course, no structure should be manually specialized, beyond tuning, to handle any particular dataset.

**Comment by andreaskipf** [comment] 2020-07-07 15:02
The new version, which we will merge some time this week, won’t handle
these outliers either. So I expect degraded performance for RS in this
case.

We plan to automatically handle such (and other types of) outliers in
future iterations of RS.

I agree, I think we should keep the new dataset.

**Comment by RyanMarcus** [comment] 2020-07-07 16:41
In the meantime, looks like the best RS config is to use a single radix bit. Tests on my desktop:

Old numbers:
```
[ryan@ryan-arch-tower SOSD]$ build/benchmark --pareto --only RS data/fb_200M_uint64 data/fb_200M_uint64_equality_lookups_10M 
Repeating lookup code 1 time(s).
Using 1 thread(s).
Only executing indexes matching RS
read 200000000 values from data/fb_200M_uint64 in 825 ms (242.424 M values/s)
data is unique
read 10000000 values from data/fb_200M_uint64_equality_lookups_10M in 75 ms (133.333 M values/s)
RESULT: RS,1,281.006,636316028,5778155784,BinarySearch
RESULT: RS,2,305.131,286466588,5279849287,BinarySearch
RESULT: RS,3,331.326,112973820,4987933362,BinarySearch
RESULT: RS,4,348.465,34267228,4846300852,BinarySearch
RESULT: RS,5,358.911,9114700,4733765847,BinarySearch
RESULT: RS,6,427.388,1941628,4670745930,BinarySearch
RESULT: RS,7,498.816,805676,4816661161,BinarySearch
RESULT: RS,8,571.965,277708,4835943355,BinarySearch
RESULT: RS,9,791.477,80220,4833923097,BinarySearch
RESULT: RS,10,855.381,22956,4848160201,BinarySearch
```

New numbers:
```
[ryan@ryan-arch-tower SOSD]$ build/benchmark --pareto --only RS data/fb_200M_uint64 data/fb_200M_uint64_equality_lookups_10M 
Repeating lookup code 1 time(s).
Using 1 thread(s).
Only executing indexes matching RS
read 200000000 values from data/fb_200M_uint64 in 821 ms (243.605 M values/s)
data is unique
read 10000000 values from data/fb_200M_uint64_equality_lookups_10M in 72 ms (138.889 M values/s)
RESULT: RS,1,772.807,502098748,5536266535,BinarySearch
RESULT: RS,2,727.458,269689644,5248179606,BinarySearch
RESULT: RS,3,679.077,108779644,4881358643,BinarySearch
RESULT: RS,4,656.597,33218684,4736136287,BinarySearch
RESULT: RS,5,626.173,8066140,4704914496,BinarySearch
RESULT: RS,6,647.496,1810572,4684253574,BinarySearch
RESULT: RS,7,685.563,740156,4674584564,BinarySearch
RESULT: RS,8,721.185,261340,4680036937,BinarySearch
RESULT: RS,9,777.845,80204,4677753423,BinarySearch
RESULT: RS,10,828.457,22924,4726326099,BinarySearch
```

As expected, a major regression. With only a spline layer, RS has the same non-monotonic behavior as many tree structures.

**Comment by andreaskipf** [comment] 2020-07-22 21:35
We have just updated RS. The new version won't handle these outliers in the immediate future.

**Closed as completed by andreaskipf** 2020-07-22 21:35 UTC
