### ISSUE TITLE
[RadixSpline] SIGSEGV on EqualityLookup when key = 0

### ISSUE THREAD

**Issue by jmftrindade** [learnedsystems/SOSD#6] opened 2020-06-11 00:25 UTC
Hi there!

We noticed that RadixSpline throws a SIGSEGV when key = 0 due to an out-of-bounds access onto the `spline` array.  The key in question is present in our input (sorted) data array.  The version of the code we have is the one with process implemented like so:

```cpp
  inline uint32_t process(uint64_t x) const {
    // Compute index.
    uint32_t index;
    const uint64_t p = (x - min_) >> shift_bits_;
    uint32_t begin = radix_hint_[p];
    uint32_t end = radix_hint_[p + 1];

    switch (end - begin) {
      case 0:
        index = end;
        break;
      case 1:
        index = (spline[begin].first >= x) ? begin : end;
        break;
      case 2:
        index = ((spline[begin].first >= x)
                     ? begin
                     : ((spline[begin + 1].first >= x) ? (begin + 1) : end));
        break;
      case 3:
        index =
            ((spline[begin].first >= x)
                 ? begin
                 : ((spline[begin + 1].first >= x)
                        ? (begin + 1)
                        : ((spline[begin + 2].first > x) ? (begin + 2) : end)));
        break;
      default:
        index =
            std::lower_bound(spline.begin() + begin, spline.begin() + end, x,
                             [](const Coord& a, const uint64_t lookup_key) {
                               return a.first < lookup_key;
                             }) -
            spline.begin();
        break;
    }

    return index - 1;
  }
```

When key = 0, `process` gets called with `x = 0`, which ends up falling into `case 2` and setting `index` to 0.  The return statement at the end is `index - 1` (or 4294967295 as `uint32_t`), which is then used as index into the `spline` array in `segmentInterpolation`, causing the out-of-bounds access.

I noticed that the latest implementation of `process` is not too different, so at a quick glance it seems that a similar bug could still be present there. We'd be interested in confirming that this out-of-bounds access is no longer present in the latest version before migrating our copy over.

Cheers,
Joana

**Comment by RyanMarcus** [comment] 2020-06-11 01:42
This somewhat affects the current implementation -- I [left a note on it](https://github.com/learnedsystems/SOSD/blob/master/competitors/radix_spline.h#L305) for Alex and Andreas to take a look at.

In the current implementation, I added a workaround by simply changing the final return statement to: 
```
return std::max(index, (uint32_t) 1) - 1;
```

In my opinion, the whole switch statement is also a needless optimization, and just be replaced with simply the `default` case.

**Comment by jmftrindade** [comment] 2020-06-11 14:54
The `std::max` call to cap index to positive values removes the SIGSEGV due to out-of-bounds access.

It seems to have introduced (or perhaps uncovered) a new issue, however.  Namely, `RadixSpline::EqualityLookup(key)` always returns 0 for `key=0` (the first key in the data set), even when the corresponding value for that key is different from 0.

This can be replicated with any input data set where the value of the first key is not 0, e.g.,:

```
{key: 0, value: 10}
```

I'm not sure if this has already been addressed in the latest version. The version we have here has the following implementation for `RadixSpline::EqualityLookup`:

```cpp
  uint64_t EqualityLookup(const KeyType lookup_key) const {
    uint64_t estimate = segmentInterpolation(process(lookup_key), lookup_key);
    return util::linear_search(data_, lookup_key, estimate);
  }

  ...

  template <class KeyType>
static inline uint64_t linear_search(const std::vector<KeyValue<KeyType>>& data,
                                     const KeyType lookup_key,
                                     int64_t estimate) {
  // NOTE: not tested for look ups where the key does not exist .. could be
  // wrong ..

#ifdef PRINT_ERRORS
  const int64_t org_estimate = estimate;
  int64_t actual_key_pos = -1;
#endif

  const int64_t limit = data.size();
  assert(0 <= estimate && estimate < limit);

  // Estimated too low
  if (data[estimate].key < lookup_key) {
    estimate++;
    while (estimate < limit && data[estimate].key < lookup_key) {
      estimate++;
    }

    uint64_t result = 0;
    while (estimate < limit && data[estimate].key == lookup_key) {
      result += data[estimate].value;
#ifdef PRINT_ERRORS
      // First encountered position == first key occurrence in forward search.
      if (actual_key_pos == -1) actual_key_pos = estimate;
#endif
      estimate++;
    }
#ifdef PRINT_ERRORS
    std::cout << org_estimate - actual_key_pos << std::endl;
#endif
    return result;
  }

  // We estimated too high
  if (data[estimate].key > lookup_key) {
    estimate--;
    while (estimate > 0 && data[estimate].key > lookup_key) {
      estimate--;
    }

    uint64_t result = 0;
    while (estimate > 0 && data[estimate].key == lookup_key) {
      result += data[estimate].value;
#ifdef PRINT_ERRORS
      // Last encountered position == first key occurrence in backwards search.
      actual_key_pos = estimate;
#endif
      estimate--;
    }
#ifdef PRINT_ERRORS
    std::cout << org_estimate - actual_key_pos << std::endl;
#endif
    return result;
  }

  // We estimated just about right
  uint64_t initial_pos = estimate;
  uint64_t result = 0;

  // Go down
  while (estimate > 0 && data[estimate].key == lookup_key) {
    result += data[estimate].value;
#ifdef PRINT_ERRORS
    // Last encountered position == first key occurrence in backwards search.
    actual_key_pos = estimate;
#endif
    estimate--;
  }

  // Go up
  estimate = initial_pos;
  estimate++;
  while (estimate < limit && data[estimate].key == lookup_key) {
    result += data[estimate].value;
    estimate++;
  }

#ifdef PRINT_ERRORS
  std::cout << org_estimate - actual_key_pos << std::endl;
#endif
  return result;
}
```

**Comment by RyanMarcus** [comment] 2020-06-11 14:57
In the new implementation, the radix spline returns offsets into the array instead of directly searching for their values. This way, 0 is always the correct answer for the key 0 (at least for unsigned data).

**Comment by jmftrindade** [comment] 2020-06-11 15:02
Alright, I'll give the new version a try then and report back if we run into issues. Thanks!

**Comment by RyanMarcus** [comment] 2020-06-11 15:48
Just so you know, there are issues with the current code as well -- sometimes there's a numerical issue with the spline the causes the estimate to be off by a bit. Should be fixed soon.

**Comment by jmftrindade** [comment] 2020-06-11 21:09
Following up on this: it now looks like all keys but the first one (key=0) are exactly off by 1. Is the `start` field of `SearchBound` (the new return type of `EqualityLookup`) supposed to be interpreted as index + 1?

Example of what I mean:
```
Testing build from input data...ok

key-value pairs:
0) (0, 1)
1) (1, 11)
2) (2, 21)
3) (3, 31)
4) (4, 41)

Testing reads...
rspline returned start=0, stop=1 for k=0
k=0 is ok!

rspline returned start=0, stop=2 for k=1
k=1, v=11, val returned was instead=1 (data_[b.start].value)

rspline returned start=1, stop=3 for k =2
k=2, v=21, val returned was instead=11 (data_[b.start].value)

rspline returned start=2, stop=4 for k=3
k=3, v=31, val returned was instead=21 (data_[b.start].value)

rspline returned start=3, stop=5 for k=4
k=4, v=41, val returned was instead=31 (data_[b.start].value)
```

Should I be using instead `stop-1`? The latter would be correct, at least for all key-value pairs in this example.

**Comment by andreaskipf** [comment] 2020-06-11 22:02
Yes, this is an artifact of that workaround. AFAIU, the key will still be
within the predicted [start, end] range (the prediction will just be off by 1
"into" the range). The reimplementation of RS won't have that issue. Thanks
for flagging this!

**Comment by andreaskipf** [comment] 2020-06-11 22:15
Following-up here (I just saw your pasted example): You still need to do a *local search* within the [start, end] search bounds to locate the key. For example, a binary search:
https://github.com/learnedsystems/SOSD/blob/master/searches/branching_binary_search.h

That you got stop=5 for k=4 seems to be another bug. stop should not exceed data_size - 1 (since end is inclusive here in SOSD). You can fix that one on your end by modifying that line:
https://github.com/learnedsystems/SOSD/blob/master/competitors/radix_spline.h#L56
uint64_t right = (estimate + est_error < data_size) ? (estimate + est_error) : data_size - 1;

**Comment by jmftrindade** [comment] 2020-06-12 22:31
Cool, thanks for following up. Forgot to follow up earlier today: confirming here that with the suggested fix and doing a local search over the returned SearchBound we correctly retrieve all inserted keys. Let me know if you'd like me to close this issue or keep it open.

**Comment by andreaskipf** [comment] 2020-06-14 21:14
Great! You can control the „width“ of the resulting search window using the
error parameter. The width is error*2. For precise models, you probably
want to use linear search around the estimated position and binary search
otherwise.

I think we can close the issue: I confirmed with Ryan: the SearchBound in
SOSD is [begin, end) so the RS implementation is actually correct (sorry
for the hiccup).

**Closed as completed** 2020-06-16 12:05 UTC
